version: '3.8'

services:
  latex:
    image: texlive/texlive:latest
    container_name: resume_service
    volumes:
      - ./workspace:/workspace
    working_dir: /workspace
    environment:
      - TZ=America/New_York
      - TEXMFHOME=/workspace/texmf
    command: tail -f /dev/null
